#! /bin/bash

cat << EOF > setup.sql 
USE mysql
FLUSH PRIVILEGES;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED by '${MYSQL_PASSWORD}';
CREATE DATABASE IF NOT EXISTS ${MYSQL_DB_NAME};
GRANT ALL PRIVILEGES ON ${MYSQL_DB_NAME}.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '${MY_SQL_ROOT_PWD}';
FLUSH PRIVILEGES;
EOF
